server:
  port: 8009
  tomcat:
    threads:
      max: 600
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${zsh.datasource.driver-class-name}
    url: jdbc:mysql://${zsh.datasource.host}:${zsh.datasource.port}/${zsh.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${zsh.datasource.username}
    password: ${zsh.datasource.password}
  redis:
    port: 6379
    host: localhost
    database: 1

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.it.pojo
  configuration:
    map-underscore-to-camel-case: true
