dubbo:
    registry:
        address:  nacos://localhost:8848
        group: dubbo-group
        parameters:
            namespace: f7fcc6e7-febc-4b33-af96-69acbbf2bdbb
    protocol:
        name: dubbo
        port: 20880
    consumer:
        check: false
        timeout: 5000
        retries: 2
server:
    port: 8000
spring:
  application:
      name: sample-dubbo-consumer