# 应用服务 WEB 访问端口
server.port=10023

# mysql数据库
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# MyBatis-Flex 配置
mybatis-flex.mapper-locations=classpath:mapper/*.xml
# 开启字段自动填充(onInsertValue/onUpdateValue)
mybatis-flex.column-on-insert=true
mybatis-flex.column-on-update=true

# redis pool配置
redis.host: 127.0.0.1
redis.port: 6379
redis.password: 123456
redis.database: 15
redis.timeout: 3000
redis.pool.max-total: 8
redis.pool.max-idle: 8
redis.pool.min-idle: 2
redis.pool.max-wait-millis: 3000
redis.pool.test-on-borrow: false

# 开启swagger
knife4j.enable=true
# 关闭swagger界面ui的认证（如需开启改为true，并配置用户名密码）
knife4j.basic.enable=false
#knife4j.basic.username=swagger
#knife4j.basic.password=swagger
