server:
    port: 7112

spring:
    config:
        import:
            - optional:classpath:bootstrap.yml

#spring:
#    application:
#        name: order-server
#    profiles:
#        active: dev
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 127.0.0.1:8848
#                namespace: public
#                group: DEFAULT_GROUP
#logging:
#    level:
#        com:
#            alibaba:
#                cloud:
#                    nacos: debug