spring:
    application:
        name: nacos-service-consumer-open-feign
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                namespace: public
                group: DEFAULT_GROUP
        openfeign:
            httpclient:
                enabled: false
            okhttp:
                enabled: true

    #        sentinel:
#            transport:
#                dashboard: localhost:8035  # Sentinel控制台地址
#                port: 8719  # 应用与Sentinel控制台交互的端口，默认8719
#            web-context-unify: false  # 关闭Web上下文的统一处理
#            eager: true  # 立即初始化

# OpenFeign配置
#feign:
#    sentinel:
#        enabled: true  # 开启Feign对Sentinel的支持


# 目标服务配置
target:
    service:
        name: nacos-service-provider

server:
    port: 7004

# 日志配置
logging:
    level:
        com.shuai.feign: DEBUG
        # OkHttp 特定日志
        okhttp3: DEBUG
        com.squareup.okhttp3: DEBUG