spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connectTimeout: 2000
            readTimeout: 2000
          service-stock:
            logger-level: full
            connectTimeout: 5000
            readTimeout: 5000