server:
  port: 8808
  tomcat:
    threads:
      max: 500
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${zsh.datasource.driver-class-name}
    url: jdbc:mysql://${zsh.datasource.host}:${zsh.datasource.port}/${zsh.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${zsh.datasource.username}
    password: ${zsh.datasource.password}
zsh:
  redisson:
    host: localhost
    port: 6379