
# 设置Log4j的根日志级别为DEBUG，并指定日志输出到控制台和文件
log4j.rootLogger=DEBUG,console,file


# 配置控制台日志输出的Appender
log4j.appender.console = org.apache.log4j.ConsoleAppender
# 设置控制台日志输出的目标为标准输出
log4j.appender.console.Target = System.out
# 设置控制台日志输出的阈值为DEBUG级别
log4j.appender.console.Threshold=DEBUG
# 配置控制台日志输出的布局为PatternLayout
log4j.appender.console.layout = org.apache.log4j.PatternLayout
# 设置控制台日志输出的格式
log4j.appender.console.layout.ConversionPattern=[%c]-%m%n



# 配置日志的Appender为滚动文件Appender，这意味着日志文件会根据一定条件滚动生成新的文件
log4j.appender.file = org.apache.log4j.RollingFileAppender
# 指定日志文件的路径和名称
log4j.appender.file.File=./log/logFile.log
# 设置日志文件的最大大小为10MB，超过这个大小后会生成新的日志文件
log4j.appender.file.MaxFileSize=10mb
# 设置日志记录的阈值为DEBUG级别，这意味着DEBUG及以上级别的日志会被记录
log4j.appender.file.Threshold=DEBUG
# 配置日志的布局为PatternLayout，即日志的输出格式将根据ConversionPattern的设置进行
log4j.appender.file.layout=org.apache.log4j.PatternLayout
# 设置日志的输出格式，包括日志级别、日期、日志类别和日志消息
# 具体格式为：[日志级别][日期][日志类别]日志消息
log4j.appender.file.layout.ConversionPattern=[%p][%d{yy-MM-dd}][%c]%m%n



# 设置MyBatis日志级别为DEBUG
log4j.logger.org.mybatis=DEBUG
# 设置Java SQL日志级别为DEBUG
log4j.logger.java.sql=DEBUG
# 设置SQL Statement日志级别为DEBUG
log4j.logger.java.sql.Statement=DEBUG
# 设置SQL ResultSet日志级别为DEBUG
log4j.logger.java.sql.ResultSet=DEBUG
# 设置SQL PreparedStatement日志级别为DEBUG
log4j.logger.java.sql.PreparedStatement=DEBUG