server.port=8001
spring.application.name=cloud-simple-provider
dubbo.scan.base-packages=com.shuai.provider.service
dubbo.protocol.name=dubbo
dubbo.protocol.port=20882
spring.cloud.zookeeper.connect-string=123.56.89.181:2181
#spring.cloud.nacos.discovery.server-addr=123.56.89.181:8848