spring:
    application:
        name: Boot_MongoDB_Code
    data:
        mongodb:
            host: 192.168.211.166
            port: 27017
            username: zsh
            password: 123456
            authentication-database: admin
            database: zsh_db
server:
    port: 8789
