server:
  port: 80

# ==========applicationName ===================
spring:
  application:
    name: cloud-consumer-service

  # ========= Spring Cloud Consul for Service Discovery =======
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

## 调用 provider 服务提供者
zsh:
  consul:
    provider-name: http://consul-payment-service