# ===================  knife4j 文档配置 =====================
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是帅哥`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.shaui.spring_security.controller

# ============== Tomcat 服务器端口 ===================
server:
  port: 8001

# ==============  mysql数据库 相关配置 ===========
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  # ============================ redis 配置 =================
  redis:
    host: 117.72.222.71
    port: 32062
    database: 0
    password: 123456

# =================   mybatis-plus 配置 ==================
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# =================  jwt 令牌 配置 =========================
jwt:
  tokenHeader: token
  tokenSignKey: coding-zsh   # 加密盐
  tokenExpiration: 3600000   # 1小时 1000 * 60 * 60 单位毫秒


