# Redis集群节点地址
redis.nodes=192.168.211.104:6379,192.168.211.104:6380,192.168.211.104:6381,192.168.211.104:6382,192.168.211.104:6383,192.168.211.104:6384

# 在集群中执行操作时要遵循的最大重定向次数
redis.cluster.max-redirects=5

# Redis数据库连接密码（默认为空）
redis.password=null
redis.timeout=30000

# 连接池最大连接数（使用负值表示没有限制）
redis.maxTotal=30

# 连接池中的最大空闲连接数
redis.maxIdle=10
redis.numTestsPerEvictionRun=1024
redis.timeBetweenEvictionRunsMillis=30000
redis.minEvictableIdleTimeMillis=1800000
redis.softMinEvictableIdleTimeMillis=10000

# 连接池获取连接时的最大等待时间（使用负值表示没有限制）
redis.maxWaitMillis=1500
redis.testOnBorrow=true
redis.testWhileIdle=true
redis.blockWhenExhausted=false
redis.JmxEnabled=true