###
GET http://localhost:8888/quartz/addJob
Accept: */*
Content-Type: application/json

{
  "jobName": "myJob",
  "groupName": "default",
  "jobClass": "cn.itcast.quartz.MyJob",
  "cronExpression": "0/5 * * * * ?",
  "param": {
    "hello": "world"
  }
}


###
GET http://192.168.200.201:8888/quartz/addJob
Accept: */*
Content-Type: application/json

{
  "jobName": "myJob2",
  "groupName": "default",
  "jobClass": "cn.itcast.quartz.MyJob",
  "cronExpression": "0/5 * * * * ?",
  "param": {
    "hello": "world"
  }
}



###
GET http://localhost:8888/quartz/deleteJob
Accept: */*
Content-Type: application/json

{
  "jobName": "myJob",
  "groupName": "default"
}


###
GET http://192.168.200.201:8888/quartz/deleteJob
Accept: */*
Content-Type: application/json

{
  "jobName": "myJob2",
  "groupName": "default"
}
