# 应用服务 WEB 访问端口
server:
    port: 9194
    # 应用服务 WEB 访问路径
    servlet:
        context-path: /

# 应用服务名称
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: multiple-datasource
    # 应用服务环境 dev,prod,test,local
    profiles:
        active: local

    # 多数据源配置
    datasource:
        # 主数据源 (MySQL)
        mysql:
            master:
                ########## JDBC 基本配置 ##########
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://${zsh.mysql.master.host}:${zsh.mysql.master.port}/${zsh.mysql.master.db-name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
                username: ${zsh.mysql.master.username}
                password: ${zsh.mysql.master.password}
                ########## 连接池 配置 ##########
                initial-size: 5
                minIdle: 10
                max-active: 20
                # 配置获取连接等待超时的时间(单位：毫秒)
                max-wait: 60000
                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
                time-between-eviction-runs-millis: 2000
                # 配置一个连接在池中最小生存的时间，单位是毫秒
                min-evictable-idle-time-millis: 600000
                max-evictable-idle-time-millis: 900000
                # 用来测试连接是否可用的SQL语句,默认值每种数据库都不相同,这是mysql
                validationQuery: select 1
                # 应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用
                testWhileIdle: true
                # 如果为true，默认是false，应用向连接池申请连接时，连接池会判断这条连接是否是可用的
                testOnBorrow: false
                # 如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
                testOnReturn: false
                # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
                poolPreparedStatements: true
                # 要启用PSCache，必须配置大于0，当大于0时， poolPreparedStatements自动触发修改为true，
                maxOpenPreparedStatements: 20
                # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
                keepAlive: true
            slave:
                ########## JDBC 基本配置 ##########
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://${zsh.mysql.slave.host}:${zsh.mysql.slave.port}/${zsh.mysql.slave.db-name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
                username: ${zsh.mysql.slave.username}
                password: ${zsh.mysql.slave.password}
                ########## 连接池 配置 ##########
                initial-size: 5
                minIdle: 10
                max-active: 20
                # 配置获取连接等待超时的时间(单位：毫秒)
                max-wait: 60000
                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
                time-between-eviction-runs-millis: 2000
                # 配置一个连接在池中最小生存的时间，单位是毫秒
                min-evictable-idle-time-millis: 600000
                max-evictable-idle-time-millis: 900000
                # 用来测试连接是否可用的SQL语句,默认值每种数据库都不相同,这是mysql
                validationQuery: select 1
                # 应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用
                testWhileIdle: true
                # 如果为true，默认是false，应用向连接池申请连接时，连接池会判断这条连接是否是可用的
                testOnBorrow: false
                # 如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
                testOnReturn: false
                # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
                poolPreparedStatements: true
                # 要启用PSCache，必须配置大于0，当大于0时， poolPreparedStatements自动触发修改为true，
                maxOpenPreparedStatements: 20
                # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
                keepAlive: true

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        cache-enabled: false
    mapper-locations: classpath*:mapper/**/*.xml